### ISSUE TITLE
Invalid CC info causes tricky modal state

### ISSUE THREAD

**Issue by stripedpajamas** [flossbank/splash#104]
Steps to reproduce:
- Add a monthly donation but put invalid CC info in
- Click Save -- it says it's invalid
- Hit Save again, the modal goes away (weird experience)

Also:
- Add a monthly donation but put invalid CC info in
- Click Save -- it says it's invalid
- "Fix" the CC info, but accidentally keep it invalid
- Hit Save again, the modal goes away (awful experience)

**Comment by joelwass** [comment]
Fixed by #116
